# Query 7

SELECT DISTINCT C.CARTON_ID, MIN(C.LEN * C.WIDTH * C.HEIGHT) AS CARTON_VOL
FROM CARTON C
WHERE C.LEN * C.WIDTH * C.HEIGHT >
(SELECT DISTINCT SUM(OI.PRODUCT_QUANTITY * P.LEN * P.WIDTH * P.HEIGHT) FROM ORDER_ITEMS OI, PRODUCT P WHERE P.PRODUCT_ID = OI.PRODUCT_ID
AND OI.ORDER_ID = 10006) ORDER BY 1;	

# Query 8

SELECT DISTINCT OC.CUSTOMER_ID, OC.CUSTOMER_FNAME||' '||OC.CUSTOMER_LNAME AS CUSTOMER_NAME,
OH.ORDER_ID, SUM(OI.PRODUCT_QUANTITY) AS TOTAL_PRODUCT
FROM ONLINE_CUSTOMER OC, ORDER_HEADER OH, ORDER_ITEMS OI
WHERE OC.CUSTOMER_ID = OH.CUSTOMER_ID
AND OH.ORDER_ID = OI.ORDER_ID 
AND OH.ORDER_STATUS = 'Shipped'
GROUP BY OH.ORDER_ID
HAVING SUM(OI.PRODUCT_QUANTITY) > 10
ORDER BY 1;


# Query 9

SELECT DISTINCT OH.ORDER_ID, OC.CUSTOMER_ID, OC.CUSTOMER_FNAME||' '||OC.CUSTOMER_LNAME AS CUSTOMER_NAME,
SUM(OI.PRODUCT_QUANTITY) AS TOTAL_QUANTITY
FROM ONLINE_CUSTOMER OC, ORDER_HEADER OH, ORDER_ITEMS OI
WHERE OC.CUSTOMER_ID = OH.CUSTOMER_ID
AND OH.ORDER_ID = OI.ORDER_ID
AND OH.ORDER_STATUS = 'Shipped'
AND OH.ORDER_ID > 10060
GROUP BY OH.ORDER_ID
ORDER BY 1;

# Query 10

SELECT DISTINCT PC.PRODUCT_CLASS_DESC, SUM(OI.PRODUCT_QUANTITY) AS TOTAL_PROD_QTY,
(OI.PRODUCT_QUANTITY * P.PRODUCT_PRICE) AS TOTAL_VALUE
FROM PRODUCT P, ADDRESS A, ONLINE_CUSTOMER OC, ORDER_HEADER OH, ORDER_ITEMS OI, PRODUCT_CLASS PC
WHERE OC.CUSTOMER_ID = OH.CUSTOMER_ID
AND OH.ORDER_ID = OI.ORDER_ID
AND OC.ADDRESS_ID = A.ADDRESS_ID
AND OI.PRODUCT_ID = P.PRODUCT_ID
AND P.PRODUCT_CLASS_CODE = PC.PRODUCT_CLASS_CODE
AND A.COUNTRY NOT IN ('India','USA')
GROUP BY PC.PRODUCT_CLASS_DESC
ORDER BY 2 DESC LIMIT 1;
